name: fuzzylogic
version: 0.3.0
description: A fuzzy logic module.
homepage: https://github.com/filiph/fuzzylogic

environment:
    sdk: ">=2.8.0 <3.0.0"

dependencies:
  logging: ^0.11.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.3.0
